Repository WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-2-Team-C, pull requests merged in 2025-01, with the labels that each got.

#112 Feature/us111/patient search by social
  client/src/components/Header/Header.tsx
  client/src/pages/AgentHome/AgentHome.tsx
  client/src/schemas/departement.schema.ts
  client/src/schemas/department.schema.ts
Labels: Need review

#116 Feature/us36/secretary view planning
  client/package-lock.json
  client/package.json
  client/src/components/RoleBasedPlanning/RoleBasedPlanning.tsx
  client/src/components/secretary_components/Agenda/Agenda.tsx
  client/src/components/secretary_components/DoctorSelector/DoctorSelector.tsx
  client/src/components/secretary_components/DoctorSelector/DoctorSelector.types.ts
  client/src/components/secretary_components/FormPanel/FormPanel.tsx
  client/src/components/secretary_components/FormPanel/FormPanel.types.ts
  client/src/generated/graphql-types.ts
  client/src/main.tsx
  client/src/pages/SecretaryHome/SecretaryHome.tsx
  client/src/schemas/department.schema.ts
  client/src/schemas/secretary.schema.ts
  core_api/src/modules/consultation/consultation.resolver.ts
  core_api/src/modules/department/department.resolver.ts
  mailer/package.json
Labels: Ready for merge

#115 Ci/playwright
  client/src/components/Header/Header.tsx
  client/src/components/Layout/pageNames.ts
  client/src/pages/Login/LoginDevButtons.tsx
  core_api/src/database/seed.dev.ts
  core_api/src/database/seed.jest.ts
  mailer/package-lock.json
  mailer/package.json
  mailer/utils/mailer.util.ts
  package.json
  playwright/.env.sample
  playwright/.github/workflows/playwright.yml
  playwright/.gitignore
  playwright/eslint.config.mjs
  playwright/package-lock.json
  playwright/package.json
  playwright/playwright.config.ts
  playwright/tests-examples/demo-todo-app.spec.ts
  playwright/tests/admin.spec.ts
  playwright/tests/agent.spec.ts
  playwright/tests/doctor.spec.ts
  playwright/tests/secretary.spec.ts
  tsconfig.json
  tsconfig.node.json
Labels: Need review

#123 Feature/admin/paging
  client/src/components/AdminPopup/AdminPopup.tsx
  client/src/components/OptionSelect/OptionSelect.tsx
  client/src/components/Pagination/Pagination.tsx
  client/src/components/Pagination/Pagination.types.ts
  client/src/components/UserList/UserList.tsx
  client/src/generated/graphql-types.ts
  client/src/pages/Admin/Admin.tsx
  client/src/schemas/userAdmin.schema.ts
  core_api/src/modules/user/user.entity.ts
  core_api/src/modules/user/user.resolver.ts
Labels: Need review

#132 Hotfix/patient search bar
  client/src/components/Layout/pageNames.ts
  client/src/components/PatientSearchBar/PatientSearchBar.tsx
Labels: Ready for merge

#124 CHORE/e2e: add readme detailing playwright setup and recommended test…
  playwright/readme-e2e.md
Labels: Need review

#131 Feature/us36/secretary view planning [Part 2]
  client/src/components/secretary_components/Agenda/Agenda.tsx
  client/src/components/secretary_components/Agenda/Agenda.types.ts
  client/src/components/secretary_components/Agenda/events.utils.ts
  client/src/pages/SecretaryHome/SecretaryHome.tsx
Labels: Need review

#137 Fix/uuids/users
  client/src/generated/graphql-types.ts
  client/src/schemas/secretary.schema.ts
  core_api/package-lock.json
  core_api/package.json
  core_api/src/database/seed.dev.ts
  core_api/src/database/seed.jest.ts
  core_api/src/modules/consultation/consultation.resolver.ts
  core_api/src/modules/user/user.entity.ts
Labels: Ready for merge

#136 Feature/us133/select patient as secretary
  client/src/components/SearchBar/SearchBar.tsx
  client/src/components/secretary_components/DoctorSelector/DoctorSelector.tsx
  client/src/components/secretary_components/FormPanel/FormPanel.tsx
  client/src/components/secretary_components/FormPanel/FormPanel.types.ts
  client/src/components/secretary_components/InputField/InputField.tsx
  client/src/components/secretary_components/InputField/InputField.types.ts
  client/src/components/secretary_components/PatientSelector/PatientSelector.tsx
  client/src/components/secretary_components/PatientSelector/PatientSelector.types.ts
  client/src/pages/SecretaryHome/SecretaryHome.tsx
  client/src/schemas/patient.schema.ts
Labels: Ready for merge

#142 Fix/uuids/consultations
  client/src/components/FileList/FileList.types.ts
  client/src/generated/graphql-types.ts
  core_api/src/database/seed.dev.ts
  core_api/src/database/seed.jest.ts
  core_api/src/modules/consultation/consultation.entity.ts
Labels: Ready for merge

#141 Chore/components tidy up
  client/src/App.tsx
  client/src/components/doctor_components/ConsultationsTimeline/ConsultationsTimeline.css
  client/src/components/doctor_components/ConsultationsTimeline/ConsultationsTimeline.tsx
  client/src/components/doctor_components/ConsultationsTimeline/ConsultationsTimeline.types.ts
  client/src/components/doctor_components/ConsultationsTimelineEvent/ConsultationsTimeLineEvent.types.ts
  client/src/components/doctor_components/ConsultationsTimelineEvent/ConsultationsTimelineEvent.tsx
  client/src/components/doctor_components/FileList/FileList.tsx
  client/src/components/doctor_components/FileList/FileList.types.ts
  client/src/components/doctor_components/PatientDetails/PatientDetails.tsx
  client/src/components/doctor_components/PatientDetails/PatientDetails.types.ts
  client/src/components/secretary_components/PatientSelector/PatientSelector.tsx
  client/src/components/shared_components/Header/Header.tsx
  client/src/components/shared_components/Header/Header.types.ts
  client/src/components/shared_components/Layout/Layout.test.tsx
  client/src/components/shared_components/Layout/Layout.tsx
  client/src/components/shared_components/Layout/Layout.types.ts
  client/src/components/shared_components/Layout/pageNames.ts
  client/src/components/shared_components/PatientSearchBar/PatientSearchBar.tsx
  client/src/components/shared_components/PatientSearchBar/PatientSearchBar.type.ts
  client/src/components/shared_components/RedirectWrapper/RedirectWrapper.tsx
  client/src/components/shared_components/RoleBasedPlanning/RoleBasedPlanning.tsx
  client/src/components/shared_components/SearchBar/SearchBar.tsx
  client/src/components/shared_components/SearchBar/SearchBar.type.ts
  client/src/main.tsx
  client/src/pages/Admin/Admin.tsx
  client/src/pages/AgentHome/AgentHome.tsx
  client/src/pages/Dossier/Dossier.tsx
  client/src/pages/DossierBrowser/DossierBrowser.tsx
Labels: Ready for merge

#122 Feature/us113/search bar patient
  client/src/components/agent_components/AgentPatientSearchBar/AgentPatientSearchBar.tsx
  client/src/components/agent_components/AgentPatientSearchBar/AgentPatientSearchBar.type.tsx
  client/src/components/agent_components/AgentSearchBar.tsx/AgentSearchBar.tsx
  client/src/components/agent_components/AgentSearchBar.tsx/AgentSearchBar.type.tsx
  client/src/pages/AgentHome/AgentHome.tsx
Labels: Need review

#145 Mailer : Send an email when a new user is created [us52]
  core_api/.env.sample
  core_api/src/modules/user/user.resolver.ts
  core_api/src/utils/email.utils.ts
  docker-compose.dev.yml
  mailer/.dockerignore
  mailer/Dockerfile
  mailer/package.json
  mailer/sampleRequests/post a mail (docker-dev).bru
  mailer/src/index.ts
  mailer/src/utils/mailer.util.ts
  mailer/src/utils/transporter.service.ts
  nginx.dev.conf
Labels: Ready for merge

#149 Feature/auth cookie
  client/src/components/shared_components/Header/Header.tsx
  client/src/components/shared_components/Layout/Layout.test.tsx
  client/src/components/shared_components/ProtectedRoute/ProtectedRoute.tsx
  client/src/components/shared_components/RedirectWrapper/RedirectWrapper.tsx
  client/src/contexts/auth/AuthContext.tsx
  client/src/contexts/auth/AuthContext.types.ts
  client/src/contexts/auth/useLogin.ts
  client/src/contexts/auth/useLogout.ts
  client/src/generated/graphql-types.ts
  client/src/main.tsx
  client/src/pages/Login/Login.tsx
  client/src/schemas/user.schema.ts
  core_api/package-lock.json
  core_api/package.json
  core_api/src/index.ts
  core_api/src/modules/user/user.entity.ts
  core_api/src/modules/user/user.resolver.ts
  core_api/src/schema.ts
  core_api/src/types/ContextType.ts
  core_api/src/utils/auth.utils.test.ts
  core_api/src/utils/auth.utils.ts
Labels: Ready for merge

#144 Feature/admin/ Update User Popup
  client/src/components/CreateUserPopup/CreateUserPopup.test.tsx
  client/src/components/CreateUserPopup/CreateUserPopup.tsx
  client/src/components/CreateUserPopup/CreateUserPopup.types.ts
  client/src/components/CreateUserPopup/Fields.tsx
  client/src/components/CreateUserPopup/RoleSelector.tsx
  client/src/components/CreateUserPopup/RoleSpecificFields.tsx
  client/src/components/CreateUserPopup/useCreateUserForm.ts
  client/src/components/UpdateUserPopup/UpdateUserPopup.tsx
  client/src/components/UserList/UserList.tsx
  client/src/pages/Admin/Admin.tsx
  client/src/schemas/userAdmin.schema.ts
  client/src/utils/roles.utils.ts
  core_api/src/modules/user/user.resolver.ts
Labels: Ready for merge

#155 Feature/us147/agent schedule appointments
  client/src/components/agent_components/AgentPatientSearchBar/AgentPatientSearchBar.tsx
  client/src/components/shared_components/Header/Header.tsx
  client/src/generated/graphql-types.ts
  client/src/pages/AgentHome/AgentHome.tsx
  client/src/schemas/agent.schema.ts
  client/src/schemas/patient.schema.ts
  core_api/src/modules/consultation/consultation.resolver.ts
  core_api/src/modules/patient/patient.resolver.ts
Labels: Modification Required

#154 Feature/access control
  client/src/main.tsx
  core_api/src/modules/consultation/consultation.resolver.ts
  core_api/src/modules/department/department.resolver.ts
  core_api/src/modules/department/department.test.ts
  core_api/src/modules/gender/gender.resolver.ts
  core_api/src/modules/patient/patient.resolver.ts
  core_api/src/modules/patient/patient.test.ts
  core_api/src/modules/role/role.resolver.ts
  core_api/src/modules/role/role.test.ts
  core_api/src/modules/user/user.resolver.ts
  core_api/src/types/MockUserType.ts
Labels: Need review

#158 Feature/us157/agent popup appointments
  client/src/components/AgentChoiceList/AgentChoiceList.tsx
  client/src/components/agent_components/AgentChoiceList/AgentChoiceList.tsx
  client/src/components/agent_components/AgentChoiceList/AgentChoiceList.type.ts
  client/src/components/agent_components/AgentModal/AgentModal.tsx
  client/src/components/agent_components/AgentModal/AgentModal.type.tsx
  client/src/components/agent_components/AgentPatientSearchBar/AgentPatientSearchBar.tsx
  client/src/components/agent_components/AgentSearchBar/AgentSearchBar.tsx
  client/src/components/agent_components/AgentSearchBar/AgentSearchBar.type.tsx
  client/src/pages/AgentHome/AgentHome.tsx
  core_api/src/modules/consultation/consultation.resolver.ts
Labels: Ready for merge

#160 Feature/us1572/agent modal appointments searchbar
  client/src/components/agent_components/AgentChoiceList/AgentChoiceList.tsx
  client/src/components/agent_components/AgentModal/AgentModal.tsx
  client/src/components/agent_components/AgentPatientSearchBar/AgentPatientSearchBar.tsx
  client/src/components/agent_components/AgentPatientSearchBar/AgentPatientSearchBar.type.tsx
  client/src/components/agent_components/AgentSearchBar/AgentSearchBar.type.tsx
  client/src/generated/graphql-types.ts
  client/src/pages/AgentHome/AgentHome.tsx
  client/src/schemas/agent.schema.ts
  core_api/src/modules/consultation/consultation.resolver.ts
Labels: Need review

#162 Setup/ci staging
  .env.staged.sample
  .github/workflows/api-integration-test.yml
  core_api/src/database/seed.dev.ts
  docker-compose.integration-api.yml
  docker-compose.staged.yml
  nginx.staging.conf
  pull_image_and_deploy.sh
Labels: Need review

#159 Feature/secretary/make appointment
  client/src/components/secretary_components/Agenda/Agenda.tsx
  client/src/components/secretary_components/Agenda/Agenda.types.ts
  client/src/components/secretary_components/SubjectSelector/SubjectSelector.tsx
  client/src/components/secretary_components/SubjectSelector/SubjectSelector.types.ts
  client/src/components/secretary_components/TimeSelector/TimeSelector.tsx
  client/src/components/secretary_components/TimeSelector/TimeSelector.types.ts
  client/src/generated/graphql-types.ts
  client/src/pages/SecretaryHome/SecretaryHome.tsx
  client/src/pages/SecretaryHome/SecretaryHome.types.ts
  client/src/schemas/secretary.schema.ts
  client/src/utils/dates.utils.ts
  core_api/src/modules/consultation/consultation.resolver.ts
  core_api/src/modules/consultation_subject/consultationSubject.resolver.ts
  core_api/src/schema.ts
Labels: Ready for merge

#163 Feature/us161/footer agent page
  client/public/images/home.svg
  client/public/images/return.svg
  client/src/components/agent_components/AgentChoiceList/AgentChoiceList.tsx
  client/src/components/agent_components/AgentFooter/AgentFooter.tsx
  client/src/components/agent_components/AgentFooter/AgentFooter.type.tsx
  client/src/components/agent_components/AgentSearchBar/AgentSearchBar.type.tsx
  client/src/pages/AgentHome/AgentHome.tsx
Labels: Need review, One review for merge

#172 Chore/global/improve style
  client/public/images/home.svg
  client/public/images/return.svg
  client/src/components/AdminPopupDoctorHour/AdminPopupDoctorHour.tsx
  client/src/components/CreateUserPopup/CreateUserPopup.tsx
  client/src/components/UpdateUserPopup/UpdateUserPopup.tsx
  client/src/components/UserList/UserList.tsx
  client/src/components/agent_components/AgentChoiceList/AgentChoiceList.tsx
  client/src/components/agent_components/AgentFooter/AgentFooter.tsx
  client/src/components/agent_components/AgentModal/AgentModal.tsx
  client/src/components/secretary_components/PatientSelector/PatientSelector.tsx
  client/src/components/shared_components/Header/Header.tsx
  client/src/components/shared_components/Layout/Layout.tsx
  client/src/index.css
  client/src/pages/Admin/Admin.tsx
  client/src/pages/AgentHome/AgentHome.tsx
  client/src/pages/Login/Login.tsx
Labels: Need review

#175 Hotfix style
  client/src/components/shared_components/Header/Header.tsx
  client/src/components/shared_components/PatientSearchBar/PatientSearchBar.tsx
Labels: Need review, One review for merge

#176 Feature/full seed
  Makefile
  client/src/components/AdminPopupDoctorHour/AdminPopupDoctorHour.tsx
  core_api/src/modules/department/department.entity.ts
  core_api/src/modules/patient/patient.entity.ts
  postgres/seed_data/import.sql
  postgres/seed_scripts/full_seed.sql
Labels: Ready for merge

#146 Feature/image upload
  .env.sample
  .env.staged.sample
  core_api/src/modules/attachment/attachment.resolver.ts
  core_api/src/schema.ts
  docker-compose.dev.yml
  docker-compose.staged.yml
  nginx.conf
  nginx.dev.conf
  upload/.dockerignore
  upload/.gitignore
  upload/Dockerfile
  upload/eslint.config.mjs
  upload/package-lock.json
  upload/package.json
  upload/sampleRequests/bruno.json
  upload/sampleRequests/login.bru
  upload/sampleRequests/post a file (docker-dev).bru
  upload/src/index.ts
  upload/src/utils/addAttachment.utils.ts
  upload/src/utils/auth.utils.ts
  upload/src/utils/uploadFile.utils.ts
  upload/tsconfig.json
Labels: Ready for merge

#182 FIX/client/planning-selects
  client/src/components/secretary_components/DoctorSelector/DoctorSelector.tsx
Labels: Ready for merge

#185 FIX : adapted Staged environement to be enable seeding
  Makefile
  docker-compose.staged.yml
Labels: Ready for merge

#177 Setup/redis
  .env.sample
  .env.staged.sample
  client/dockerfile
  core_api/dockerfile
  core_api/jest.setup.ts
  core_api/package-lock.json
  core_api/package.json
  core_api/src/modules/consultation/consultation.resolver.ts
  core_api/src/modules/department/department.resolver.ts
  core_api/src/services/cache/cacheMiddleware.ts
  core_api/src/services/cache/cacheService.ts
  docker-compose.dev.yml
  docker-compose.staged.yml
Labels: Need review, One review for merge

#173 Fix: fix a better accésibilité for image in button
  client/src/components/agent_components/AgentFooter/AgentFooter.tsx
Labels: Need review, One review for merge

#190 Feature/doctor planning
  client/src/components/secretary_components/Agenda/Agenda.types.ts
  client/src/components/shared_components/Agenda/Agenda.tsx
  client/src/components/shared_components/Agenda/Agenda.types.ts
  client/src/components/shared_components/Agenda/events.utils.ts
  client/src/components/shared_components/RoleBasedPlanning/RoleBasedPlanning.tsx
  client/src/pages/DoctorHome/DoctorHome.tsx
  client/src/pages/SecretaryHome/SecretaryHome.tsx
Labels: Need review, One review for merge

#194 Fix: reset all states when returning to the home view on the agent page
  client/src/pages/AgentHome/AgentHome.tsx
Labels: Need review, One review for merge

#195 Bugfix/time zone
  client/src/components/shared_components/Agenda/events.utils.ts
  client/src/generated/graphql-types.ts
  client/src/pages/SecretaryHome/SecretaryHome.tsx
  client/src/pages/SecretaryHome/SecretaryHome.types.ts
  client/src/schemas/secretary.schema.ts
  core_api/src/modules/consultation/consultation.resolver.ts
Labels: Need review

#191 fix: Change code to be ok for new data
  client/src/components/agent_components/AgentModal/AgentModal.tsx
  client/src/components/agent_components/AgentPatientSearchBar/AgentPatientSearchBar.tsx
  client/src/pages/AgentHome/AgentHome.tsx
  client/src/utils/dates.utils.ts
  core_api/src/modules/consultation/consultation.resolver.ts
  core_api/src/modules/patient/patient.resolver.ts
Labels: Need review
